language: r
warnings_are_errors: false
sudo: required
dist: trusty
cache: packages

python:
  - "2.7"

before_install:
  - pip install numpy mwparserfromhell

env:
 global:
   - CRAN: http://cran.rstudio.com
r_packages:
   - testthat
   - reticulate
   - devtools
notifications:
  email:
    on_failure: change
