language: r
warnings_are_errors: false
sudo: required
dist: trusty

python:
  - "pypy"
  - "2.7"

install:
  - pip install numpy mwparserfromhell

env:
 global:
   - CRAN: http://cran.rstudio.com
r_packages:
   - testthat
   - reticulate
notifications:
  email:
    on_failure: change
